### ISSUE TITLE
Um comentario

### ISSUE THREAD

**Issue by Madarinha-dev** [MarinaAraujoMaciel/Python_para_Zumbis#1]
desculpar pertubar ai mas tava dando uma olhada no seu repositorio e gostei muito dele, de todos os exercicios que eu fiz do canal curso em video o seu ta de parabens, gostei muito tambem sou novo na programação em python e estou em git agora, tchau e desculpa atrapalhar ai fuiii

**Comment by MarinaAraujoMaciel** [comment]
# Oii @Madarinha-dev, tudo bem?
Muito obrigada pelo comentário, estarei dando uma olhada no seu GitHub também.

**Comment by Madarinha-dev** [comment]
de nada
